name: 'Build and release'

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: 'Build artifacts and publish'
    runs-on: macos-14
    outputs:
      tag-name: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          ref: main
      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: 'Build native executables'
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: linkReleaseExecutableMacosX64
      - name: 'export version number'
        id: tag
        run: ./gradlew properties -q | grep "version:" | awk '{ print "::set-output name=tag::"$2 }'
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            ./build/bin/macosX64/releaseExecutable/scroll-kt.kexe
          tag_name: ${{steps.tag.outputs.tag}}
          name: version v${{steps.tag.outputs.tag}}