name: 'Build and release'

on: workflow_dispatch

jobs:
  build:
    name: 'Build artifacts and publish'
    runs-on: macos-12
    outputs:
      tag-name: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: 'Build native executables'
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: linkReleaseExecutableMacosX64
      - name: 'export version number'
        id: tag
        run: ./gradlew properties -q | grep "version:" | awk '{ print "::set-output name=tag::"$2 }'
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./shared/build/bin/*/releaseExecutable/google-auth-decode-*exe
          tag_name: ${{steps.tag.outputs.tag}}
          name: version v${{steps.tag.outputs.tag}}