name: 'Build and release'

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: 'Build artifacts and publish'
    runs-on: macos-15
    outputs:
      tag-name: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v6
        with:
          ref: main
      - name: 'Set up Java'
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: 'Build app and installer'
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: packageInstaller
      - name: 'Compress .app bundle'
        run: |
          cd build/dist
          zip -r ScrollKT.app.zip ScrollKT.app
      - name: 'export version number'
        id: tag
        run: |
          VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v2.5.2
        with:
          files: |
            ./build/dist/ScrollKT.app.zip
            ./build/dist/ScrollKT.pkg
          tag_name: ${{steps.tag.outputs.tag}}
          name: version v${{steps.tag.outputs.tag}}