name: Gradlew testDebug and lintDebug

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: linkReleaseExecutableMacosX64